import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import { useBusinesses } from '../lib/BusinessContext'
import { useI18n } from '../lib/i18n'
import type { HoursIn } from '../lib/types'
const DAY_LABELS_AR = ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت']; const DAY_LABELS_EN = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
function blankWeek(isRamadan: boolean): HoursIn[] { return Array.from({ length: 7 }, (_, day_of_week) => ({ day_of_week, open_time: '10:00', close_time: '22:00', is_closed: false, is_ramadan: isRamadan })) }
export default function Availability() {
  const { lang } = useI18n(); const { selectedId } = useBusinesses(); const [mode, setMode] = useState<'normal' | 'ramadan'>('normal'); const [normal, setNormal] = useState<HoursIn[]>(blankWeek(false)); const [ramadan, setRamadan] = useState<HoursIn[]>(blankWeek(true)); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!selectedId) return; api.getBusiness(selectedId).then((d) => { const n = d.hours.filter((h) => !h.is_ramadan); const r = d.hours.filter((h) => h.is_ramadan); if (n.length === 7) setNormal(n); if (r.length === 7) setRamadan(r) }) }, [selectedId])
  if (!selectedId) return <p className="text-sm text-ink-400">{lang === 'ar' ? 'اختر منشأة أولاً' : 'Select a business first'}</p>
  const active = mode === 'normal' ? normal : ramadan; const setActive = mode === 'normal' ? setNormal : setRamadan
  async function save() { if (!selectedId) return; setSaving(true); try { await api.putHours(selectedId, [...normal, ...ramadan]) } finally { setSaving(false) } }
  return <div className="space-y-4"><div className="inline-flex rounded-lg border border-ink-200 bg-surface p-1"><button onClick={() => setMode('normal')} className={`rounded-md px-4 py-1.5 text-sm font-medium ${mode === 'normal' ? 'bg-moss-600 text-white' : 'text-ink-500'}`}>{lang === 'ar' ? 'الأيام العادية' : 'Regular days'}</button><button onClick={() => setMode('ramadan')} className={`rounded-md px-4 py-1.5 text-sm font-medium ${mode === 'ramadan' ? 'bg-moss-600 text-white' : 'text-ink-500'}`}>{lang === 'ar' ? 'رمضان' : 'Ramadan'}</button></div><div className="space-y-2">{active.map((h, i) => <div key={i} className="grid grid-cols-[70px_1fr_1fr_auto] items-center gap-3 rounded-lg border border-ink-100 bg-surface px-3 py-2.5"><span className="text-sm font-medium text-ink-700">{lang === 'ar' ? DAY_LABELS_AR[i] : DAY_LABELS_EN[i]}</span><input type="time" disabled={h.is_closed} value={h.open_time ?? ''} onChange={(e) => update(i, { open_time: e.target.value })} className="input disabled:opacity-40" /><input type="time" disabled={h.is_closed} value={h.close_time ?? ''} onChange={(e) => update(i, { close_time: e.target.value })} className="input disabled:opacity-40" /><label className="flex items-center gap-1.5 text-xs text-ink-500"><input type="checkbox" checked={h.is_closed} onChange={(e) => update(i, { is_closed: e.target.checked })} className="h-3.5 w-3.5 rounded border-ink-300" />{lang === 'ar' ? 'مغلق' : 'Closed'}</label></div>)}</div><div className="flex justify-end"><button onClick={save} disabled={saving} className="rounded-lg bg-moss-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-moss-700 disabled:opacity-60">{saving ? (lang === 'ar' ? 'جاري الحفظ...' : 'Saving…') : lang === 'ar' ? 'حفظ ساعات العمل' : 'Save hours'}</button></div><p className="text-xs text-ink-400">{lang === 'ar' ? 'لتفعيل جدول رمضان فعلياً للعملاء، فعّل "وضع رمضان" من صفحة الإعدادات.' : 'To actually activate the Ramadan schedule for customers, enable "Ramadan mode" on the Settings page.'}</p></div>
  function update(index: number, patch: Partial<HoursIn>) { setActive((prev) => prev.map((h, i) => (i === index ? { ...h, ...patch } : h))) }
}
