import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import { useBusinesses } from '../lib/BusinessContext'
import { useI18n } from '../lib/i18n'
import type { BotTone, BusinessDetail } from '../lib/types'

const TONES: { value: BotTone; ar: string; en: string }[] = [
  { value: 'friendly', ar: 'ودود', en: 'Friendly' }, { value: 'professional', ar: 'احترافي', en: 'Professional' },
  { value: 'luxury', ar: 'راقي', en: 'Premium' }, { value: 'concise', ar: 'مختصر', en: 'Concise' },
]

export default function Settings() {
  const { lang } = useI18n(); const { selectedId, refresh } = useBusinesses()
  const [detail, setDetail] = useState<BusinessDetail | null>(null)
  const [profile, setProfile] = useState({ name_ar: '', name_en: '', phone: '', maps_url: '', vat_number: '', cr_number: '' })
  const [settings, setSettingsState] = useState<Record<string, string>>({})
  const [saving, setSaving] = useState<string | null>(null)
  useEffect(() => { if (!selectedId) return; api.getBusiness(selectedId).then((d) => { setDetail(d); setProfile({ name_ar:d.business.name_ar,name_en:d.business.name_en,phone:d.business.phone,maps_url:d.business.maps_url,vat_number:d.business.vat_number ?? '',cr_number:d.business.cr_number ?? '' }); setSettingsState(d.settings) }) }, [selectedId])
  if (!selectedId || !detail) return <p className="text-sm text-ink-400">{lang === 'ar' ? 'اختر منشأة أولاً' : 'Select a business first'}</p>
  async function saveProfile() { setSaving('profile'); try { await api.putProfile(selectedId!, { ...profile, vat_number: profile.vat_number || null, cr_number: profile.cr_number || null }); await refresh() } finally { setSaving(null) } }
  async function saveSettings(keys:string[]) { setSaving(keys[0]); try { const patch:Record<string,string>={}; for(const k of keys) patch[k]=settings[k] ?? ''; await api.putSettings(selectedId!,patch) } finally { setSaving(null) } }
  return <div className="space-y-6">
    <Card title={lang==='ar'?'بيانات المنشأة':'Business profile'}><div className="grid gap-4 sm:grid-cols-2"><Field label={lang==='ar'?'اسم المنشأة بالعربي':'Name (Arabic)'}><input className="input" value={profile.name_ar} onChange={(e)=>setProfile({...profile,name_ar:e.target.value})}/></Field><Field label={lang==='ar'?'اسم المنشأة بالإنجليزي':'Name (English)'}><input dir="ltr" className="input" value={profile.name_en} onChange={(e)=>setProfile({...profile,name_en:e.target.value})}/></Field><Field label={lang==='ar'?'رقم واتساب':'WhatsApp number'}><input dir="ltr" className="input" value={profile.phone} onChange={(e)=>setProfile({...profile,phone:e.target.value})}/></Field><Field label={lang==='ar'?'رابط Google Maps':'Google Maps link'}><input dir="ltr" className="input" value={profile.maps_url} onChange={(e)=>setProfile({...profile,maps_url:e.target.value})}/></Field><Field label={lang==='ar'?'الرقم الضريبي':'VAT number'}><input className="input" value={profile.vat_number} onChange={(e)=>setProfile({...profile,vat_number:e.target.value})}/></Field><Field label={lang==='ar'?'السجل التجاري':'CR number'}><input className="input" value={profile.cr_number} onChange={(e)=>setProfile({...profile,cr_number:e.target.value})}/></Field></div><SaveButton onClick={saveProfile} loading={saving==='profile'} lang={lang}/></Card>
    <Card title={lang==='ar'?'شخصية البوت':'Bot personality'}><div className="grid gap-4 sm:grid-cols-2"><Field label={lang==='ar'?'اسم البوت بالعربي':'Bot name (Arabic)'}><input className="input" value={settings.bot_name_ar ?? ''} onChange={(e)=>setSettingsState({...settings,bot_name_ar:e.target.value})}/></Field><Field label={lang==='ar'?'اسم البوت بالإنجليزي':'Bot name (English)'}><input dir="ltr" className="input" value={settings.bot_name_en ?? ''} onChange={(e)=>setSettingsState({...settings,bot_name_en:e.target.value})}/></Field></div><Field label={lang==='ar'?'الأسلوب':'Tone'}><div className="flex flex-wrap gap-2">{TONES.map((tone)=><button key={tone.value} onClick={()=>setSettingsState({...settings,bot_tone:tone.value})} className={`rounded-full border px-4 py-1.5 text-sm font-medium transition ${settings.bot_tone===tone.value?'border-moss-600 bg-moss-600 text-white':'border-ink-200 text-ink-600 hover:border-moss-400'}`}>{lang==='ar'?tone.ar:tone.en}</button>)}</div></Field><div className="grid gap-4 sm:grid-cols-2"><Field label={lang==='ar'?'رسالة ترحيب عربية':'Arabic welcome'}><textarea rows={3} className="input" value={settings.welcome_ar ?? ''} onChange={(e)=>setSettingsState({...settings,welcome_ar:e.target.value})}/></Field><Field label={lang==='ar'?'رسالة ترحيب إنجليزية':'English welcome'}><textarea dir="ltr" rows={3} className="input" value={settings.welcome_en ?? ''} onChange={(e)=>setSettingsState({...settings,welcome_en:e.target.value})}/></Field></div><SaveButton onClick={()=>saveSettings(['bot_name_ar','bot_name_en','bot_tone','welcome_ar','welcome_en'])} loading={saving==='bot_name_ar'} lang={lang}/></Card>
    <Card title={lang==='ar'?'قواعد الحجز':'Booking rules'}><Toggle checked={settings.ramadan_mode==='true'} onChange={(v)=>setSettingsState({...settings,ramadan_mode:String(v)})} label={lang==='ar'?'تفعيل جدول رمضان':'Enable Ramadan schedule'} help={lang==='ar'?'استخدم ساعات رمضان بدلاً من الجدول العادي.':'Use Ramadan hours instead of the regular schedule.'}/><Toggle checked={settings.prayer_buffer_enabled==='true'} onChange={(v)=>setSettingsState({...settings,prayer_buffer_enabled:String(v)})} label={lang==='ar'?'حجب وقت الصلاة':'Block time around prayer'} help={lang==='ar'?'يمنع المواعيد حول أوقات الصلاة.':'Prevents bookings around prayer times.'}/><div className="grid gap-4 sm:grid-cols-2"><Field label={lang==='ar'?'مدة الحجب حول الصلاة (دقائق)':'Prayer buffer (minutes)'}><input type="number" className="input" value={settings.prayer_buffer_min ?? '30'} onChange={(e)=>setSettingsState({...settings,prayer_buffer_min:e.target.value})}/></Field><Field label={lang==='ar'?'الفاصل بين الأوقات المتاحة (دقائق)':'Slot interval (minutes)'}><input type="number" className="input" value={settings.slot_interval_min ?? '30'} onChange={(e)=>setSettingsState({...settings,slot_interval_min:e.target.value})}/></Field></div><SaveButton onClick={()=>saveSettings(['ramadan_mode','prayer_buffer_enabled','prayer_buffer_min','slot_interval_min'])} loading={saving==='ramadan_mode'} lang={lang}/></Card>
    <Card title={lang==='ar'?'سياسة الإلغاء':'Cancellation policy'}><div className="grid gap-4 sm:grid-cols-2"><Field label={lang==='ar'?'العربية':'Arabic'}><textarea rows={4} className="input" value={settings.cancellation_policy_ar ?? ''} onChange={(e)=>setSettingsState({...settings,cancellation_policy_ar:e.target.value})}/></Field><Field label={lang==='ar'?'الإنجليزية':'English'}><textarea dir="ltr" rows={4} className="input" value={settings.cancellation_policy_en ?? ''} onChange={(e)=>setSettingsState({...settings,cancellation_policy_en:e.target.value})}/></Field></div><SaveButton onClick={()=>saveSettings(['cancellation_policy_ar','cancellation_policy_en'])} loading={saving==='cancellation_policy_ar'} lang={lang}/></Card>
  </div>
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="space-y-4 rounded-xl2 border border-ink-100 bg-surface p-5 shadow-card"><h3 className="text-sm font-semibold text-ink-900">{title}</h3>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-medium text-ink-500">{label}</span>{children}</label>}
function Toggle({checked,onChange,label,help}:{checked:boolean;onChange:(v:boolean)=>void;label:string;help:string}){return <label className="flex items-start justify-between gap-4 rounded-lg border border-ink-100 bg-canvas p-3.5"><div><p className="text-sm font-medium text-ink-900">{label}</p><p className="text-xs text-ink-500">{help}</p></div><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)} className="mt-1 h-4 w-4 shrink-0 rounded border-ink-300 text-moss-600"/></label>}
function SaveButton({onClick,loading,lang}:{onClick:()=>void;loading:boolean;lang:'ar'|'en'}){return <div className="flex justify-end"><button onClick={onClick} disabled={loading} className="rounded-lg bg-moss-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-moss-700 disabled:opacity-60">{loading?(lang==='ar'?'جاري الحفظ...':'Saving…'):lang==='ar'?'حفظ':'Save'}</button></div>}
