function renderOverview(){if(!detail)return;let b=detail.business;$('heroBusinessName').textContent=lang==='ar'?b.name_ar:b.name_en;$('heroSub').textContent=(b.phone||'')+(b.maps_url?' · '+(lang==='ar'?'الموقع محفوظ':'Map saved'):'');$('servicesCount').textContent=(detail.services||[]).length;let now=new Date(),todayKey=dayKey(now);let active=appointmentsCache.filter(a=>a.status!=='cancelled');$('todayCount').textContent=active.filter(a=>dayKey(new Date(a.start_time))===todayKey).length;$('upcomingCount').textContent=active.filter(a=>new Date(a.start_time)>=now).length;let next=active.filter(a=>new Date(a.start_time)>=now).sort((a,b)=>new Date(a.start_time)-new Date(b.start_time)).slice(0,5);$('nextAppointments').innerHTML=next.length?next.map(a=>`<div class="appointmentItem"><div><strong>${escapeHtml(a.customer_name||a.customer_phone)}</strong><small>${escapeHtml(lang==='ar'?a.name_ar:a.name_en)} · ${formatDate(a.start_time)}</small></div><span class="pill">${escapeHtml(a.status)}</span></div>`).join(''):`<div class="emptyList">${t('noBookings')}</div>`}
async function refreshConnection(){if(!current)return;let badge=$('waBadge');badge.className='statusBadge waiting';badge.querySelector('b').textContent=t('checking');try{let d=await api(`/api/businesses/${current}/connection`);let state=((d.instance||d||{}).state||'').toLowerCase();let connected=['open','connected'].includes(state);let tested=false;if(connected){try{let s=await api(`/api/businesses/${current}/conversation-test-status`);tested=!!s.ok}catch{tested=false}}badge.className='statusBadge '+(connected?'connected':'offline');badge.querySelector('b').textContent=connected?t('connected'):t('notConnected');$('waChecklist').classList.toggle('done',connected);$('testChecklist').classList.toggle('done',tested);$('readyChecklist').classList.toggle('done',tested);$('waChecklist').querySelector('.check').textContent=connected?'✓':'2';$('testChecklist').querySelector('.check').textContent=tested?'✓':'3';$('readyChecklist').querySelector('.check').textContent=tested?'✓':'4';if(connected){$('qrWrap').classList.add('hidden');$('liveTestBox').classList.remove('hidden')}else{$('liveTestBox').classList.add('hidden');await qr()}}catch{badge.className='statusBadge offline';badge.querySelector('b').textContent=t('notConnected');$('testChecklist').classList.remove('done');$('readyChecklist').classList.remove('done');await qr().catch(()=>{})}}
function showQr(q){if(!q)return;$('qrWrap').classList.remove('hidden');$('qr').src=q.startsWith('data:')?q:'data:image/png;base64,'+q}
async function qr(){if(!current)return;let d=await api(`/api/businesses/${current}/qr`);if(d.qr)showQr(d.qr)}
$('refreshQr').onclick=async()=>{await qr();toast(lang==='ar'?'تم تحديث QR':'QR refreshed')};
$('sendLiveTest').onclick=async()=>{try{
  let phone=normalizePhone($('liveTestPhone').value);
  if(!phone)throw Error(lang==='ar'?'أدخل رقم اختبار صحيح.':'Enter a valid test number.');
  let d=await api(`/api/businesses/${current}/test-message`,{method:'POST',body:JSON.stringify({phone,language:$('liveTestLang').value})});
  $('liveTestResult').textContent=lang==='ar'?'تم الإرسال. رد الآن من واتساب ثم اضغط "تحقق من الرد".':'Sent. Reply from WhatsApp, then press "Check reply".';
  toast(lang==='ar'?'تم إرسال رسالة الاختبار':'Test message sent');
}catch(e){$('liveTestResult').textContent=e.message;toast(e.message,true)}};
$('checkLiveTest').onclick=async()=>{try{
  let d=await api(`/api/businesses/${current}/conversation-test-status`);
  if(d.ok){
    $('liveTestResult').textContent=(lang==='ar'?'تم استلام رد واتساب الحقيقي ✅ ':'Real WhatsApp reply received ✅ ')+(d.last_inbound_phone||'');
    $('testChecklist').classList.add('done');$('testChecklist').querySelector('.check').textContent='✓';$('readyChecklist').classList.add('done');$('readyChecklist').querySelector('.check').textContent='✓';toast(lang==='ar'?'اختبار واتساب مكتمل':'WhatsApp test complete');
  }else{
    $('liveTestResult').textContent=lang==='ar'?'لم يصل رد بعد. أرسل أي رسالة من رقم الاختبار.':'No reply received yet. Send any message from the test number.';
  }
}catch(e){toast(e.message,true)}};

$('refreshOverview').onclick=async()=>{await loadDetail();toast(t('saved'))};
function renderServices(){let box=$('serviceEditor');box.innerHTML='';(detail?.services||[]).forEach(s=>addServiceRow(s))}
function addServiceRow(s={}){let div=document.createElement('div');div.className='serviceRow';div.dataset.id=s.id||'';div.innerHTML=`<label><span>العربية</span><input value="${escapeAttr(s.name_ar||'')}" placeholder="قص شعر"></label><label><span>English</span><input value="${escapeAttr(s.name_en||'')}" placeholder="Haircut" dir="ltr"></label><label><span>${t('duration')} (${t('minutes')})</span><input type="number" min="1" value="${s.duration_min||30}"></label><label><span>${t('price')} (${t('sar')})</span><input type="number" min="0" step="0.01" value="${s.price||0}"></label><label><span>${t('buffer')} (${t('minutes')})</span><input type="number" min="0" value="${s.buffer_min||0}"></label><button class="deleteBtn" type="button" title="${t('delete')}">×</button>`;div.querySelector('.deleteBtn').onclick=()=>div.remove();box.appendChild(div)}
$('addService').onclick=()=>addServiceRow();
$('saveServices').onclick=async()=>{try{let items=[...document.querySelectorAll('.serviceRow')].map(r=>{let i=r.querySelectorAll('input');return{id:r.dataset.id||null,name_ar:i[0].value,name_en:i[1].value,duration_min:+i[2].value,price:+i[3].value,buffer_min:+i[4].value}}).filter(x=>x.name_ar&&x.name_en);if(!items.length)throw Error(lang==='ar'?'أضف خدمة واحدة على الأقل.':'Add at least one service.');await api(`/api/businesses/${current}/services`,{method:'PUT',body:JSON.stringify(items)});await loadDetail();toast(t('saved'))}catch(e){toast(e.message,true)}};
const dayNames={ar:['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'],en:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']};
function renderHours(items){let map=new Map((items||[]).map(h=>[`${h.is_ramadan}-${h.day_of_week}`,h]));let box=$('hoursEditor');box.innerHTML='';for(let ram of [false,true]){let group=document.createElement('div');group.className='hourGroup '+((ram&&hoursMode==='ramadan')||(!ram&&hoursMode==='normal')?'active':'');group.dataset.group=ram?'ramadan':'normal';for(let d=0;d<7;d++){let x=map.get(`${ram}-${d}`)||{day_of_week:d,open_time:'10:00',close_time:'22:00',is_closed:false,is_ramadan:ram};let div=document.createElement('div');div.className='hourRow';div.dataset.day=d;div.dataset.ramadan=ram;div.innerHTML=`<span class="dayName">${dayNames[lang][d]}</span><input type="time" value="${(x.open_time||'10:00').slice(0,5)}"><input type="time" value="${(x.close_time||'22:00').slice(0,5)}"><label class="closedLabel"><input type="checkbox" ${x.is_closed?'checked':''}> ${t('closed')}</label>`;group.appendChild(div)}box.appendChild(group)}}
document.querySelectorAll('[data-hours-mode]').forEach(b=>b.onclick=()=>{hoursMode=b.dataset.hoursMode;document.querySelectorAll('[data-hours-mode]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.hourGroup').forEach(x=>x.classList.toggle('active',x.dataset.group===hoursMode))});
